name: main
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DENO_DIR: /tmp/.deno
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
    - uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: deno-${{ runner.os }}
    - run: deno task lcov
    - uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ github.token }}
        path-to-lcov: .cov-profile/cov.lcov
