name: main
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DENO_DIR: /tmp/.deno
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
    - uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: deno-${{ runner.os }}
    - run: deno task lcov
    - uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ github.token }}
        path-to-lcov: .cov-profile/cov.lcov

  npm:
    needs: [test]
    runs-on: ubuntu-22.04
    env:
      DENO_DIR: /tmp/.deno
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: deno-${{ runner.os }}
    - run: |
        set -exv
        if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
          deno task dnt "$GITHUB_REF_NAME"
        else
          deno task dnt 0.0.0
        fi
        pushd npm/
        npm pack --dry-run
        if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
          npm publish --access=public
        else
          npm publish --access=public --dry-run
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
